import numpy as np


class Extend():
    """This."""

    def __init__(self, Traj, System, Metadata, Names, Outfile='Extended.xyz'):
        """
        Parameters.

        ----------
        
        Traj : ase atoms object
            This will be typically read into the class directly from the
            Process object. However, a user may also call seperately and in
            this case must pre-call the ase atoms object before this class.
            
        System : python dictionary
            Dictionary of basic analysis parameters provided by both the
            user and the System_Clean module.
            
        Metadata : python dictionary
            This is the dictionary style outpute of Sapphire which contains
            all of the relevant analysed information for facile reading/writing.
            
        Names : list of strings
            The names of the quantities to be hunted for in the metadata.
            These will need to be given precisely as they are named in the
            documentation. Two additional names may also be provided.
            
            E1NN : How many nearest neighbours each atom has which are atomic
            type 1. At present, this is crudely implemented.
            
            E2NN : How many nearest neighbours each atom has which are atomic
            type 2. At present, this is crudely implemented.

        Returns
        -------
        None.
        But it will write the extended xyz file or die trying.

        """
        self.System = System
        self.Base = self.System['base_dir']
        self.Metadata = Metadata
        self.Names = []
        self.Quants = []
        self.Traj = Traj
        self.Outfile = Outfile
        for name in Names:
            if name in Metadata:
                self.Names.append(name)
                self.Quants.append(Metadata[name])
            else:
                with open(self.Base + 'Sapphire_Errors.log', 'a') as f:
                    f.write("Sapphire is cowardly unwilling to write %s into the extended xyz file: "
                            "no such quantity in the run output.\n" % name)
        self.ExtendXYZ()

    def ExtendXYZ(self):
        """Write a multi-frame xyz: per frame ``N``, a comment naming the extra columns, then
        ``symbol x y z <extra columns...>`` for every atom."""
        n_frames = min([len(self.Traj)] + [len(q) for q in self.Quants]) if self.Quants else len(self.Traj)
        with open(self.Base + self.Outfile, 'w') as movie:
            for i in range(n_frames):
                atoms = self.Traj[i]
                items = np.column_stack((atoms.get_chemical_symbols(), atoms.positions))
                cols = []
                for name, obj in zip(self.Names, self.Quants):
                    try:
                        items = np.column_stack((items, obj[i]))
                        cols.append(str(name))
                    except Exception as e:
                        with open(self.Base + 'Sapphire_Errors.log', 'a') as f:
                            f.write("Sapphire is cowardly unwilling to write %s (frame %d) into the extended xyz "
                                    "file with error traceback:\n%s\n" % (name, i, e))
                movie.write(str(len(atoms)) + '\n')
                movie.write('Extended xyz generated by Sapphire | frame %d | extra columns: %s\n' % (i, ' '.join(cols)))
                for atom in items:
                    movie.write(' \t'.join(str(item) for item in atom) + '\n')
